version: '3.8'

services:
  # PHP Service
  php:
    container_name: php_container
    build:
      context: .
      target: php
      args:
        - APP_PORT=${APP_PORT}
        - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - ${APP_PORT}:8000
    networks:
      - api-network
    depends_on:
      - database

  # Database Service
  database:
    container_name: database_container
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=${DB_USERNAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_DATABASE}
    networks:
      - api-network
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: ~

networks:
  api-network:
    driver: bridge
